apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    hello-world-app
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      hello-world-app
  template:
    metadata:
      labels:
        hello-world-app
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: hello-world-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
