apiVersion: apps/v1
kind: Deployment
metadata:
  name: multy-deployment
  labels:
    app: nginx
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      app: apache
  template:
    metadata:
      labels:
        app: nginx
        app: apache
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 81
      - name: apache
        image: httpd:alpine
        ports:
        - containerPort: 82
