#apiVersion: v1
#kind: Service
#metadata:
#  name: my-svc-apache-clusterip
#spec:
#  selector:
#    app: apache
#  ports:
#  - name: http
#    protocol: TCP
#    port: 8090
#   targetPort: 80
#---
apiVersion: v1
kind: Service
metadata:
  name: svc-apache-nodeport
spec:
  type: NodePort
  selector:
    app: apache
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 80
    NodePort: 30090
#---
#apiVersion: v1
##kind: Pod
#metadata:
#  name: busybox
#  labels:
#    app: apache-deployment
#spec:
#  containers:
#  - name: busybox
#    image: busybox
#    ports:
#    - containerPort: 80
#    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:alpine
        ports:
        - containerPort: 80